### PR TITLE
log exception and throw it if developer mode

### PR DESCRIPTION
**Pull request by zainengineer**
@willtran please CR

### CODE REVIEW

**Comment by willtran** [comment]
It doesn't hurt but I don't really see why it's required either?
On local dev environment you can put a breakpoint inside the catch statement for debug, on staging / prod the log file should be sufficient? 
Need another set of eyes @jonpday @aligentjim

**Comment by zainengineer** [comment]
it does two things
1) logException which is useful on staging/production to find why feed is failing
2) In developer mode makes it easier for dev to catch any issues, instead of going through logs

**Comment by aligentjim** [comment]
I think the logging of the exception is a good thing.  However I'm wary of re-throwing the exception in developer mode.  If the exception is important enough to stop execution then it should stop execution in all modes, not just developer mode.

In general, I'm wary of code that changes it's behavior (as opposed to just changing the verbosity of logging or output) in developer mode vs production mode.  So I agree with @willtran, this is better achieved with a break point.  Keep the extra logging though.

**Comment by willtran** [comment]
On that note would be great to consider using Aligent_Feeds_Model_Log

**Comment by zainengineer** [comment]
@aligentjim removed the throwing error part.

**Pull request merged**
